services:
  nginx:
    image: nginx:latest
    ports:
      - "1313:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  web:
    environment:
      - PORT=1313
    depends_on:
      - database-postgres
      - database-redis
  database-postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  database-redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
