services:
  web:
    ports:
      - "1313:1313"
    environment:
      - PORT=1313
    depends_on:
      - database
  database:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
